services:
#    dri_exit.example:
#        class: DRI\ExitBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    twig.extension.exits:
        class: DRI\ExitBundle\Twig\Extension\DRIExitExtension
        tags:
            - { name: twig.extension }

    namer.ext_app_dco_files:
        class: DRI\ExitBundle\Service\ExtAppDCONamer
        tags:
            - { name: namer }

    namer.ext_mis_wps_files:
        class: DRI\ExitBundle\Service\ExtMisWPSNamer
        tags:
            - { name: namer }

    namer.ext_dep_res_files:
        class: DRI\ExitBundle\Service\ExtDepRESNamer
        tags:
            - { name: namer }

    DRI\ExitBundle\Form\DepartureType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]