services:
#    dri_exit.example:
#        class: DRI\ExitBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    namer.exit_wps_files:
        class: DRI\ExitBundle\Service\ExitWPSNamer
        tags:
            - { name: namer }

    namer.departure_results_files:
        class: DRI\ExitBundle\Service\DepartureResultsNamer
        tags:
            - { name: namer }

    DRI\ExitBundle\Form\DepartureType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]