services:

#   TWIG EXTENSIONS
    twig.extension.exits:
        class: DRI\ExitBundle\Twig\Extension\DRIExitExtension
        tags:
            - { name: twig.extension }

#   DATATABLES CLASSES
    app.datatable.exits.application:
        class: DRI\ExitBundle\Datatables\ApplicationDatatable
        parent: sg_datatables.datatable.abstract

    app.datatable.exits.departure:
        class: DRI\ExitBundle\Datatables\DepartureDatatable
        parent: sg_datatables.datatable.abstract


#   NAMER CLASSES
    namer.ext_app_dco_files:
        class: DRI\ExitBundle\Service\ExtAppDCONamer
        tags:
            - { name: namer }

    namer.ext_mis_wps_files:
        class: DRI\ExitBundle\Service\ExtMisWPSNamer
        tags:
            - { name: namer }

    namer.ext_dep_res_files:
        class: DRI\ExitBundle\Service\ExtDepRESNamer
        tags:
            - { name: namer }

#   FORMTYPE CLASES
    DRI\ExitBundle\Form\DepartureType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]