services:
#    usuario.example:
#        class: UsuarioBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    namer.users_images:
        class: DRI\UserBundle\Service\UserNamer
        tags:
            - { name: namer }