<?php

namespace DRI\ForeingStudentBundle\Repository;

/**
 * UndergraduateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostgraduateRepository extends \Doctrine\ORM\EntityRepository
{
}
