<?php

namespace DRI\ForeingStudentBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\AST\Functions\FunctionNode;

use DRI\ForeingStudentBundle\Entity\Undergraduate;


/**
 * UndergraduateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UndergraduateRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTypeAndGender($type, $gender){
        $em = $this->getEntityManager();

        $dql = 'SELECT u
                FROM DRIForeingStudentBundle:Undergraduate u
                WHERE u.type = :type AND u.gender = :gender
                ORDER BY u.createdAt DESC';

        $query = $em->createQuery($dql);
        $query->setParameter('type', $type);
        $query->setParameter('gender',$gender);

        return $query->getResult();
    }

    public function findCountryAndType($country, $type = null ){
        $em = $this->getEntityManager();

        if($type){
            $dql = 'SELECT u
                    FROM DRIForeingStudentBundle:Undergraduate u
                    WHERE u.country = :country AND u.type = :type
                    ORDER BY u.createdAt DESC';
        }else{
            $dql = 'SELECT u
                    FROM DRIForeingStudentBundle:Undergraduate u
                    WHERE u.country = :country
                    ORDER BY u.createdAt DESC';
        }
        $query = $em->createQuery($dql);
        $query->setParameter('country',$country);
        if($type)
            $query->setParameter('type', $type);

        return $query->getResult();
    }

    public function findCountryAndGender($country, $gender){
        $em = $this->getEntityManager();

        $dql = 'SELECT u
                FROM DRIForeingStudentBundle:Undergraduate u
                WHERE u.country = :country AND u.gender = :gender
                ORDER BY u.createdAt DESC';

        $query = $em->createQuery($dql);
        $query->setParameter('country', $country);
        $query->setParameter('gender',$gender);

        return $query->getResult();
    }

    public function findCountryAndGenderAndType($country, $gender, $type = null){
        $em = $this->getEntityManager();

        if($type){
            $dql = 'SELECT u
                    FROM DRIForeingStudentBundle:Undergraduate u
                    WHERE u.country = :country AND u.gender = :gender AND u.type = :type
                    ORDER BY u.createdAt DESC';
        }else{
            $dql = 'SELECT u
                    FROM DRIForeingStudentBundle:Undergraduate u
                    WHERE u.country = :country AND u.gender = :gender
                    ORDER BY u.createdAt DESC';
        }
        $query = $em->createQuery($dql);
        $query->setParameter('country', $country);
        $query->setParameter('gender',$gender);
        if($type)
            $query->setParameter('type',$type);

        return $query->getResult();
    }

}
