<?php

namespace DRI\AgreementBundle\Repository;

/**
 * NationalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalRepository extends \Doctrine\ORM\EntityRepository
{
}
