<?php

namespace DRI\AgreementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NationalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalRepository extends EntityRepository
{
}
