services:
#    dri_passport.example:
#        class: DRI\PassportBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    twig.extension.passports:
        class: DRI\PassportBundle\Twig\Extension\DRIPassportExtension
        tags:
            - { name: twig.extension }

    namer.passports_images:
        class: DRI\PassportBundle\Service\PassportNamer
        tags:
            - { name: namer }