dri_exit_manager_travel_plan:
    resource: "@DRIExitBundle/Controller/ManagerTravelPlanController.php"
    type:     annotation

dri_foreing_student:
    resource: "@DRIForeingStudentBundle/Controller/"
    type:     annotation
    prefix:   /foreing-student

dri_useful_course:
    resource: "@DRIUsefulBundle/Controller/CourseController.php"
    type:     annotation

dri_useful_career:
    resource: "@DRIUsefulBundle/Controller/CareerController.php"
    type:     annotation

dri_agreement_application:
    resource: "@DRIAgreementBundle/Controller/ApplicationController.php"
    type:     annotation

dri_agreement_institution:
    resource: "@DRIAgreementBundle/Controller/InstitutionController.php"
    type:     annotation

dri_agreement_institutional:
    resource: "@DRIAgreementBundle/Controller/InstitutionalController.php"
    type:     annotation

_dashboard:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: dashboard }

dri_system:
    resource: "@DRISystemBundle/Controller/"
    type:     annotation
    prefix:   /

dri_client:
    resource: "@DRIClientBundle/Controller/"
    type:     annotation
    prefix:   /client

dri_passport:
    resource: "@DRIPassportBundle/Controller/"
    type:     annotation
    prefix:   /passport

dri_exit:
    resource: "@DRIExitBundle/Controller/"
    type:     annotation
    prefix:   /exit

dri_agreement:
    resource: "@DRIAgreementBundle/Controller/"
    type:     annotation
    prefix:   /agreement

dri_useful:
    resource: "@DRIUsefulBundle/Controller/"
    type:     annotation
    prefix:   /useful

dri_user_user:
    resource: "@DRIUserBundle/Controller/UserController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation

_imagecrop_bundle:
    resource: "@ImageCropBundle/Resources/config/routing.yml"

presta_image:
    resource: "@PrestaImageBundle/Resources/config/routing.yml"
