services:

#   TWIG EXTENSIONS

#   DATATABLES CLASSES
    app.datatable.foreingstudents.posgraduate:
        class: DRI\ForeingStudentBundle\Datatables\PostgraduateDatatable
        parent: sg_datatables.datatable.abstract

    app.datatable.foreingstudents.undergraduate:
        class: DRI\ForeingStudentBundle\Datatables\UndergraduateDatatable
        parent: sg_datatables.datatable.abstract


#   NAMER CLASSES
    namer.undergraduates_pictures:
        class: DRI\ForeingStudentBundle\Service\UndergraduatePictureNamer
        tags:
            - { name: namer }
    namer.postgraduates_pictures:
        class: DRI\ForeingStudentBundle\Service\PostgraduatePictureNamer
        tags:
            - { name: namer }