services:
#    dri_foreing_student.example:
#        class: DRI\ForeingStudentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    namer.undergraduates_pictures:
        class: DRI\ForeingStudentBundle\Service\UndergraduatePictureNamer
        tags:
            - { name: namer }
    namer.postgraduates_pictures:
        class: DRI\ForeingStudentBundle\Service\PostgraduatePictureNamer
        tags:
            - { name: namer }