services:

#   TWIG EXTENSIONS
    twig.extension.clients:
        class: DRI\ClientBundle\Twig\Extension\DRIClientExtension
        tags:
            - { name: twig.extension }


#   DATATABLES CLASSES
    app.datatable.clients.client:
        class: DRI\ClientBundle\Datatables\ClientDatatable
        parent: sg_datatables.datatable.abstract


#   NAMER CLASSES
    namer.clients_images:
        class: DRI\ClientBundle\Service\ClientImageNamer
        tags:
            - { name: namer }