services:
#    dri_client.example:
#        class: DRI\ClientBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    namer.clients_images:
        class: DRI\ClientBundle\Service\ClientImageNamer
        tags:
            - { name: namer }