services:
#    dri_client.example:
#        class: DRI\ClientBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    twig.extension.clients:
        class: DRI\ClientBundle\Twig\Extension\DRIClientExtension
        tags:
            - { name: twig.extension }

    namer.clients_images:
        class: DRI\ClientBundle\Service\ClientImageNamer
        tags:
            - { name: namer }