<?php

namespace DRI\UsefulBundle\Repository;

/**
 * FacultadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends \Doctrine\ORM\EntityRepository
{
}
