<?php

namespace DRI\UsefulBundle\Repository;

/**
 * CareerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareerRepository extends \Doctrine\ORM\EntityRepository
{
}
