<?php

namespace DRI\UsefulBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * CareerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareerRepository extends EntityRepository
{
}
