<?php

namespace DRI\PassportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlRepository extends EntityRepository
{
}
