<?php

namespace DRI\PassportBundle\Repository;

/**
 * PasaporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassportRepository extends \Doctrine\ORM\EntityRepository
{
}
