services:

#   TWIG EXTENSIONS
    twig.extension.agreements:
        class: DRI\AgreementBundle\Twig\Extension\DRIAgreementExtension
        tags:
            - { name: twig.extension }

#   DATATABLES CLASSES
    app.datatable.agreements.application:
        class: DRI\AgreementBundle\Datatables\ApplicationDatatable
        parent: sg_datatables.datatable.abstract

    app.datatable.agreements.institutional:
        class: DRI\AgreementBundle\Datatables\InstitutionalDatatable
        parent: sg_datatables.datatable.abstract

    app.datatable.agreements.institution:
        class: DRI\AgreementBundle\Datatables\InstitutionDatatable
        parent: sg_datatables.datatable.abstract

#   NAMER CLASSES
    namer.institutions_logos:
        class: DRI\AgreementBundle\Service\InstitutionLogoNamer
        tags:
            - { name: namer }

    namer.agr_int_dco_files:
        class: DRI\AgreementBundle\Service\AgrIntDCONamer
        tags:
            - { name: namer }
