<?php

namespace DRI\ExitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandFileRepository extends EntityRepository
{
}
