<?php

namespace DRI\ExitBundle\Repository;

/**
 * CommandFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandFileRepository extends \Doctrine\ORM\EntityRepository
{
}
