<?php

namespace DRI\ExitBundle\Repository;

/**
 * DepartureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartureRepository extends \Doctrine\ORM\EntityRepository
{
}
