<?php

namespace DRI\ExitBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EconomicRepository extends \Doctrine\ORM\EntityRepository
{
}
