<?php

namespace DRI\ExitBundle\Repository;

/**
 * ExitApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExitApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
