<?php

namespace DRI\ExitBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\AST\Functions\FunctionNode;
use DRI\ExitBundle\Entity\ManagerTravelPlan;

/**
 * ManagerTravelPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerTravelPlanRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCurrentPlan(){
        $em = $this->getEntityManager();

        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->where('YEAR(p.createdAt) = :year')
            ->andWhere('p.canceled = :canceled')
        ;

        $qb->setParameter('year', date('Y'));
        $qb->setParameter('canceled', false);

        $plan = $qb->getQuery()->getResult();

        return $plan;
    }

    public function getOldPlan($year){
        $em = $this->getEntityManager();

        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->where('YEAR(p.createdAt) = :year')
            ->andWhere('p.canceled = :canceled')
        ;

        $qb->setParameter('year', $year - 1);
        $qb->setParameter('canceled', false);

        $plan = $qb->getQuery()->getResult();

        return $plan;
    }

    public function getOldPlans(){
        $em = $this->getEntityManager();

        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->where('YEAR(p.createdAt) < :year')
            ->andWhere('p.canceled = :canceled')
        ;

        $qb->setParameter('year', date('Y'));
        $qb->setParameter('canceled', false);

        $plan = $qb->getQuery()->getResult();

        return $plan;
    }


}
