services:

#   TWIG EXTENSIONS
    twig.extension.fechas:
        class: DRI\UsefulBundle\Twig\Extension\DRIUsefulExtension
        tags:
            - { name: twig.extension }

#   DATATABLES CLASSES
    app.datatable.useful.country:
        class: DRI\UsefulBundle\Datatables\CountryDatatable
        parent: sg_datatables.datatable.abstract

    app.datatable.useful.area:
        class: DRI\UsefulBundle\Datatables\AreaDatatable
        parent: sg_datatables.datatable.abstract

    datatable.server_side:
        class: DRI\UsefulBundle\Handler\DatatableServerSide
        arguments: ["@doctrine.orm.entity_manager"]

    datatable.handler_request:
        class: DRI\UsefulBundle\Handler\RequestHandler
        arguments: ["@doctrine.orm.entity_manager"]

#   NAMER CLASSES
    namer.countries_flags_images:
        class: DRI\UsefulBundle\Service\CountriesFlagsNamer
        tags:
            - { name: namer }

